version: '3'

services:
  static:
    command: npm start
    ports:
      # open for hmr websocket communication
      # details in static/package.json
      - "7001:7001"

  web:
    image: nginx
    environment:
      - STATIC_LOCATION=http://static:7001
    volumes:
      - ./nginx/server.dev.template:/etc/nginx/conf.d/server.template
