env:
  browser: true
  es6: true
  node: true

extends:
  - 'plugin:react/recommended'
  - 'plugin:mocha/recommended'
  - 'standard'

parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2019
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
  - mocha
  - react

rules:
#  FIXME: allow to use until I add logging lib
#  https://github.com/fire-marshal/fire-marshal/issues/35
#  no-console:
#    - error
#    - allow:
#      - warn
#      - error

  linebreak-style:
    - error
    - unix

  # allow to use UNSAFE React functions
  # https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
  camelcase:
    - error
    - allow:
      - '^UNSAFE_'

settings:
  react:
    version: 16.6.3
